apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.appName }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  EXPIRATION_DAYS: "{{ .Values.data.expirationDays }}"
  REDIS_GROUP_HOST: "{{ .Values.data.redisGroupHost }}"
  REDIS_GROUP_PORT: "{{ .Values.data.redisGroupPort }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.data.springProfilesActive }}"
  {{- if not .Values.onPremEnabled }}
  GOOGLE_AUDIENCES: "{{ .Values.data.googleAudiences }}"
  {{- end }}
